{
 "title": "EnviroStation",
 "description": "Air Quality Monitoring Station",
 "tags": [
  "PM10",
  "PM2.5",
  "Temperature",
  "Humidity",
  "Environmental",
  "Air Quality",
  "Particulate"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PM10 Particulate Mass [ug/m3]",
   "type": "graph",
   "description": "PM10 Readings \n\n(Airborn Particulate  Matter <10 um)\n\n@ Location = South Darenth",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "PM10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Max PM10 Reading\n\n<24 h",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "PM10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "title": "Temperature [DegC]",
   "type": "graph",
   "description": "Temperature @\nLocation = South Darenth",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Max PM2.5 Reading\n\n<24 h",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "PM25",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "title": "PM2.5 Particulate Mass [ug/m3]",
   "type": "graph",
   "description": "PM2.5 Readings \n\n(Airborn Particulate  Matter <2.5um)\n\n@ Location = South Darenth\n\n",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "PM25",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "title": "Humidity [%]",
   "type": "graph",
   "description": "Humidity @\nLocation = South Darenth",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Max PM10 Reading\n\n<24 h",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Max PM10 Reading\n\n<24 h",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Max Humidity\n\n<24 h",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Current PM2.5 Reading\n\n<24 h",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "PM25",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Current PM10 Reading\n\n<24 h",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "PM10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "southdarenth" }
     ]
    }
   ]
  }
 ]
}